language: ruby

rvm:
  - 1.9.3

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq s3cmd

install:
  - bundle install

script:
  - bundle exec jekyll build
  - mv _site apidocs-$TRAVIS_BUILD_NUMBER
  - tar -cjvf apidocs-$TRAVIS_BUILD_NUMBER.tar.bz2 apidocs-$TRAVIS_BUILD_NUMBER

env:
  secure: "ZIbLd/T7aK3l3tIH3JylFYA6Vd7pRiNwqtBhh4PVbrDjltX6Kg46v//LXCCi5bmL4eaRwiQftzg1Cm9P0ds7UILa7FGEtBb/2+cHfPypGYWodHmA8Vedc5wb+IIJIREirtMNYmolOojy9Kupf/yhXdhTkIBqxjELFhliZjP5ARc="

after_success:
  - chmod 755 .travis/deploy.sh
  - .travis/deploy.sh

notifications:
  email: false
  hipchat:
    rooms:
      - c92bad93fc0d9c2d195d80c7be121a@Orchestrate
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} %{build_url}'

