language: python
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
branches:
  only:
  - master
before_script:
- pip install coverage coveralls
script:
- coverage run --source=porc setup.py test
after_success:
- coveralls
env:
  global:
    secure: IAJSzMFnItV6ILzFIDBd5VMVc0MDlD69hNKV59oRruU265CI2ZkNaqjBor+QbgkTsWi8Asr0m4BGh3AScs4Ijq+R6u6VrX3Q+pOukK7vVfWeDqZXhYXbtvXT/EhVbHjRJGy5myy4yKWD+zIqp5dGJb/WE+muDOViro99ns+fNg0=
