language: python
python: 
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
branches:
  only:
    - master
before_script:
  - pip install coverage coveralls
script:
  - coverage run --source=porc setup.py test
after_success:
  - coveralls